version: '3.8'
services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports: 
      - 8000:8000
    volumes: 
      - .:/app
    depends_on: 
      - db
  
  queue:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on: 
      - db
    
  db:
    image: postgres:13-alpine
    restart: always
    volumes: 
      - .dbdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=dbname
      - POSTGRES_USER=rootuser
      - POSTGRES_PASSWORD=changeme
    ports: 
      - 5432:5432